# Generated by Django 4.1.7 on 2024-02-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_deliveryservice_speed_unit_deliveryservice_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryservice',
            name='user',
        ),
    ]
