# Generated by Django 4.1.7 on 2024-02-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_deliveryservice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryservice',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
