# Generated by Django 4.1.7 on 2024-02-14 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0006_alter_deliveryservice_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='myDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='myParcelDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_contents', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAttrModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_attr', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='usersBookingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', models.BooleanField(default=False)),
                ('parcels_details_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.myparceldetailsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_details_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.mydetailsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='mydetailsmodel',
            name='user_attr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.userattrmodel'),
        ),
    ]
