# Generated by Django 4.1.7 on 2024-02-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_mydetailsmodel_myparceldetailsmodel_userattrmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliveryDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='returnDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=5)),
            ],
        ),
    ]
