# Generated by Django 4.1.7 on 2024-02-24 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0009_deliveryguaranteeoptions_alter_mydetailsmodel_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_model_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePacketingDeliveryMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_data_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.deliverydetailsdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_booking_data_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.usersbookingdata')),
            ],
        ),
    ]
