# Generated by Django 4.1.7 on 2024-02-25 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_serviceusermodel_servicepacketingdeliverymainmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepacketingdeliverymainmodel',
            name='service_data_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.serviceusermodel'),
        ),
    ]
