# Generated by Django 4.1.7 on 2024-02-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_servicepacketingdeliverymainmodel_service_data_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
