# Generated by Django 4.1.7 on 2024-02-26 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_serviceusermodel_service_model_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepacketingdeliverymainmodel',
            name='delivery_data_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.deliverydetailsdata'),
        ),
    ]
