# Generated by Django 4.1.7 on 2024-02-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_servicepacketingdeliverymainmodel_delivery_data_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepacketingdeliverymainmodel',
            name='user_booking_data_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.usersbookingdata'),
        ),
    ]
