# Generated by Django 4.1.7 on 2024-02-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_deliveryservice_servicemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepacketingdeliverymainmodel',
            name='serviceModelInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicemodel'),
        ),
    ]
