# Generated by Django 5.0.3 on 2024-04-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_usersbookingdata_service_data_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryservice',
            name='sale_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
