# Generated by Django 5.0.3 on 2024-04-03 11:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_deliveryservice_sale_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryservice',
            name='sale_percentage',
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_discount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.deliveryservice')),
            ],
        ),
    ]
