# Generated by Django 5.0.3 on 2024-04-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_remove_deliveryservice_sale_salesdata_delete_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceusermodel',
            name='sale_applied',
            field=models.BooleanField(default=False),
        ),
    ]
